<?php
defined('BASEPATH') OR exit('No direct script access allowed');
$config['mysql_host'] = 'localhost';
$config['mysql_username'] = 'id7663012_anupanel';
$config['mysql_password'] = 'passwordb_anda';
$config['mysql_database'] = 'id7663012_anumks';
$config['mysql_driver'] = 'mysqli';
$config['mysql_charset'] = 'utf8';
$config['mysql_dbcollat'] = 'utf8_general_ci';
$config['base_js'] = 'assets/js';
$config['base_css'] = 'assets/css';
$config['base_plugins'] = 'assets/plugins';
$config['base_images'] = 'assets/images';
$config['base_fonts'] = 'assets/font-awesome';
$config['other_base'] = 'assets/fonts';
$config['email_author'] = 'spiritcode@cyberpassnet.com';
$config['instagram_author'] = 'Spiritcode';
$config['twitter_author'] = '#';
$config['limit'] = 7;
$config['title'] = 'Cyberpassnet';
